# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.5.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QFrame, QLabel,
    QLineEdit, QListView, QListWidget, QListWidgetItem,
    QPushButton, QSizePolicy, QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(710, 683)
        self.additem_line_edit = QLineEdit(Widget)
        self.additem_line_edit.setObjectName(u"additem_line_edit")
        self.additem_line_edit.setGeometry(QRect(120, 130, 471, 31))
        font = QFont()
        font.setFamilies([u"Poppins"])
        self.additem_line_edit.setFont(font)
        self.additem_line_edit.setStyleSheet(u"background-color: rgb(236, 221, 214);")
        self.my_list = QListWidget(Widget)
        self.my_list.setObjectName(u"my_list")
        self.my_list.setGeometry(QRect(120, 230, 471, 331))
        self.my_list.setMinimumSize(QSize(0, 150))
        font1 = QFont()
        font1.setFamilies([u"Poppins"])
        font1.setPointSize(10)
        self.my_list.setFont(font1)
        self.my_list.setFrameShape(QFrame.NoFrame)
        self.my_list.setFrameShadow(QFrame.Plain)
        self.my_list.setLineWidth(0)
        self.my_list.setSelectionMode(QAbstractItemView.SingleSelection)
        self.my_list.setSpacing(4)
        self.my_list.setViewMode(QListView.ListMode)
        self.clear_all = QPushButton(Widget)
        self.clear_all.setObjectName(u"clear_all")
        self.clear_all.setGeometry(QRect(350, 180, 93, 29))
        self.clear_all.setFont(font)
        self.delete_item = QPushButton(Widget)
        self.delete_item.setObjectName(u"delete_item")
        self.delete_item.setGeometry(QRect(250, 180, 93, 29))
        self.delete_item.setFont(font)
        self.add_item = QPushButton(Widget)
        self.add_item.setObjectName(u"add_item")
        self.add_item.setGeometry(QRect(130, 180, 111, 29))
        self.add_item.setFont(font)
        self.ekspor = QPushButton(Widget)
        self.ekspor.setObjectName(u"ekspor")
        self.ekspor.setGeometry(QRect(130, 560, 141, 29))
        self.ekspor.setFont(font)
        self.impor = QPushButton(Widget)
        self.impor.setObjectName(u"impor")
        self.impor.setGeometry(QRect(290, 560, 141, 29))
        self.impor.setFont(font)
        self.ekspor_pdf = QPushButton(Widget)
        self.ekspor_pdf.setObjectName(u"ekspor_pdf")
        self.ekspor_pdf.setGeometry(QRect(130, 600, 141, 29))
        self.ekspor_pdf.setFont(font)
        self.keterangan = QLabel(Widget)
        self.keterangan.setObjectName(u"keterangan")
        self.keterangan.setGeometry(QRect(130, 210, 311, 20))
        font2 = QFont()
        font2.setFamilies([u"Poppins"])
        font2.setPointSize(7)
        self.keterangan.setFont(font2)
        self.keterangan.setStyleSheet(u"#keterangan{\n"
"	color: rgb(255, 0, 0);\n"
"}")
        self.exit = QPushButton(Widget)
        self.exit.setObjectName(u"exit")
        self.exit.setGeometry(QRect(670, 10, 31, 31))
        self.exit.setCursor(QCursor(Qt.PointingHandCursor))
        icon = QIcon()
        icon.addFile(u"sit.png", QSize(), QIcon.Normal, QIcon.Off)
        self.exit.setIcon(icon)
        self.exit.setCheckable(False)
        self.update = QPushButton(Widget)
        self.update.setObjectName(u"update")
        self.update.setGeometry(QRect(450, 180, 101, 29))
        self.update.setFont(font)
        self.label = QLabel(Widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(90, 70, 531, 581))
        self.label.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_2 = QLabel(Widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(250, 20, 231, 91))
        font3 = QFont()
        font3.setFamilies([u"Poppins"])
        font3.setPointSize(36)
        font3.setBold(False)
        self.label_2.setFont(font3)
        self.label_3 = QLabel(Widget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(0, 0, 711, 681))
        self.label_3.setStyleSheet(u"background-color: rgb(236, 221, 214);")
        self.line = QFrame(Widget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(120, 250, 471, 20))
        self.line.setStyleSheet(u"color: rgb(236, 221, 214);")
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line_2 = QFrame(Widget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(120, 280, 471, 20))
        self.line_2.setStyleSheet(u"color: rgb(236, 221, 214);")
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_3 = QFrame(Widget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(120, 310, 471, 20))
        self.line_3.setStyleSheet(u"color: rgb(236, 221, 214);")
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.line_4 = QFrame(Widget)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(120, 340, 471, 20))
        self.line_4.setStyleSheet(u"color: rgb(236, 221, 214);")
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.line_5 = QFrame(Widget)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(120, 370, 471, 20))
        self.line_5.setStyleSheet(u"color: rgb(236, 221, 214);")
        self.line_5.setFrameShape(QFrame.HLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.line_6 = QFrame(Widget)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(120, 400, 471, 20))
        self.line_6.setStyleSheet(u"color: rgb(236, 221, 214);")
        self.line_6.setFrameShape(QFrame.HLine)
        self.line_6.setFrameShadow(QFrame.Sunken)
        self.line_7 = QFrame(Widget)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(120, 430, 471, 20))
        self.line_7.setStyleSheet(u"color: rgb(236, 221, 214);")
        self.line_7.setFrameShape(QFrame.HLine)
        self.line_7.setFrameShadow(QFrame.Sunken)
        self.line_8 = QFrame(Widget)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(120, 460, 471, 20))
        self.line_8.setStyleSheet(u"color: rgb(236, 221, 214);")
        self.line_8.setFrameShape(QFrame.HLine)
        self.line_8.setFrameShadow(QFrame.Sunken)
        self.line_9 = QFrame(Widget)
        self.line_9.setObjectName(u"line_9")
        self.line_9.setGeometry(QRect(120, 490, 471, 20))
        self.line_9.setStyleSheet(u"color: rgb(236, 221, 214);")
        self.line_9.setFrameShape(QFrame.HLine)
        self.line_9.setFrameShadow(QFrame.Sunken)
        self.line_10 = QFrame(Widget)
        self.line_10.setObjectName(u"line_10")
        self.line_10.setGeometry(QRect(120, 520, 471, 20))
        self.line_10.setStyleSheet(u"color: rgb(236, 221, 214);")
        self.line_10.setFrameShape(QFrame.HLine)
        self.line_10.setFrameShadow(QFrame.Sunken)
        self.label_3.raise_()
        self.label.raise_()
        self.additem_line_edit.raise_()
        self.my_list.raise_()
        self.clear_all.raise_()
        self.delete_item.raise_()
        self.add_item.raise_()
        self.ekspor.raise_()
        self.impor.raise_()
        self.ekspor_pdf.raise_()
        self.keterangan.raise_()
        self.exit.raise_()
        self.update.raise_()
        self.label_2.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.line_5.raise_()
        self.line_6.raise_()
        self.line_7.raise_()
        self.line_8.raise_()
        self.line_9.raise_()
        self.line_10.raise_()

        self.retranslateUi(Widget)

        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Widget", None))
        self.additem_line_edit.setInputMask("")
        self.additem_line_edit.setPlaceholderText(QCoreApplication.translate("Widget", u"Masukkan List Kegiatan", None))
#if QT_CONFIG(tooltip)
        self.my_list.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.clear_all.setText(QCoreApplication.translate("Widget", u"Clear List", None))
        self.delete_item.setText(QCoreApplication.translate("Widget", u"Hapus Item", None))
        self.add_item.setText(QCoreApplication.translate("Widget", u"Tambah Item", None))
        self.ekspor.setText(QCoreApplication.translate("Widget", u"Export Excel", None))
        self.impor.setText(QCoreApplication.translate("Widget", u"Import", None))
        self.ekspor_pdf.setText(QCoreApplication.translate("Widget", u"Export PDF", None))
        self.keterangan.setText("")
        self.exit.setText("")
        self.update.setText(QCoreApplication.translate("Widget", u"Update", None))
        self.label.setText("")
        self.label_2.setText(QCoreApplication.translate("Widget", u"To Do List", None))
        self.label_3.setText("")
    # retranslateUi

